services:
  - type: web
    name: qd-builder
    env: docker
    dockerfilePath: ./dockerfile   # match filename
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

